version: '3.9'

services:
  postgres2:
    image: postgres:13
    environment:
      POSTGRES_DB: server1_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres2_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    container_name: auth
    build: .
    ports:
      - "8081:8081"
    depends_on:
      postgres2:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: server1_db

volumes:
  postgres2_data:
