version: '3.9'

services:
  postgres1:
    image: postgres:13
    environment:
      POSTGRES_DB: server1_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    container_name: auth
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "host=postgres1 port=5432 user=postgres password=1111 dbname=server1_db sslmode=disable"
    depends_on:
      - postgres1 

volumes:
  postgres_data:
